Обновлён tar-1.34

diff --git a/base/tar/ABUILD b/base/tar/ABUILD
--- a/base/tar/ABUILD
+++ b/base/tar/ABUILD
@@ -1,14 +1,15 @@
 pkgname=tar
-pkgver=1.32
+pkgver=1.34
 pkgbuild=1
 arch=("auto")
 
-shortdesc=("Archiving utility")
-longdesc=("This is the GNU version of tar, an archiving program designed to store and extract files from an archive file known as a tarfile. A tarfile may be made on a tape drive, however, it is also common to write a tarfile to a normal file. Slackware's package system uses tarfiles compressed with GNU gzip.")
+shortdesc="Utility used to store, backup, and transport files"
+longdesc="This is the GNU version of tar, an archiving program designed to store and extract files from an archive file known as a tarfile. A tarfile may be made on a tape drive, however, it is also common to write a tarfile to a normal file. Slackware's package system uses tarfiles compressed with GNU gzip."
 
 tags=("base app-arch")
 
-build_deps="glibc-solibs"
+build_deps="glibc"
+
 adddep="bash"
 
 source=("ftp://ftp.gnu.org/gnu/$pkgname/$pkgname-$pkgver.tar.bz2"
@@ -16,62 +17,38 @@ source=("ftp://ftp.gnu.org/gnu/$pkgname/$pkgname-$pkgver.tar.bz2"
 
 
 before_build() {
-	go_src_dir
-	# fix build failure with glibc-2.16
-	sed -i -e '/gets is a/d' gnu/stdio.in.h
+  go_src_dir
+# fix build failure with glibc-2.16
+  sed -i -e '/gets is a/d' gnu/stdio.in.h
 
-	# Build tar 1.13 
-	# At present, old tar is used only for package packing. Maybe, we can get rid of it, but heavy testing is required.
-	tar xf ${srcache}/tar-1.13.tar.gz
-	cd tar-1.13
-	zcat $filedir/tar-1.13.bzip2.diff.gz | patch -p1 --verbose || exit 1
+# Build tar 1.13
+# Most tar versions destroy symlinks!!!
+# Therefore tar-1.13 is only used for packaging packages.
+# The makepkg script can work with more recent versions, but you may need to add new options to the script. 
+  tar xf ${srcache}/tar-1.13.tar.gz
+  cd tar-1.13
+  zcat $filedir/tar-1.13.bzip2.diff.gz | patch -p1 --verbose || exit 1
 
-	# The original config.{guess,sub} do not work on x86_64
-	cp -p /usr/share/libtool/config/config.{guess,sub} .
-	chown -R root:root .
-	CFLAGS="$SLKCFLAGS" \
-		./configure \
-		--prefix=/usr \
-		--disable-nls \
-		--build=$ARCH-slackware-linux
-	make ${numjobs} || make || exit 1
-	mkdir -p ${pkgdir}/bin
-	cat src/tar > ${pkgdir}/bin/tar-1.13
-	chmod 0755 ${pkgdir}/bin/tar-1.13
-	# End building of tar-1.13
-
-	go_src_dir
-	export FORCE_UNSAFE_CONFIGURE=1
+# The original config.{guess,sub} do not work on x86_64
+#  cp -p /usr/share/libtool/config/config.{guess,sub} .
+  chown -R root:root .
+  CFLAGS="$SLKCFLAGS" \
+  ./configure \
+    --prefix=/usr \
+    --disable-nls
+  make ${numjobs} || make || exit 1
+  mkdir -p ${pkgdir}/usr/bin
+  cat src/tar > ${pkgdir}/usr/bin/tar-1.13
+  chmod 0755 ${pkgdir}/usr/bin/tar-1.13
+# End building of tar-1.13
 }
 
-BUILD_SYSTEM="autotools"
-BUILD_KEYS="--prefix=/usr \
-	--infodir=/usr/info \
-	--docdir=/usr/share/doc/tar-${pkgver} \
-	--enable-backup-scripts"
-
-INSTALL_KEYS="DESTDIR=$pkgdir"
-after_build() {
-	mkdir -p ${pkgdir}/bin
-	mv ${pkgdir}/usr/bin/tar ${pkgdir}/bin
-	( cd ${pkgdir}/usr/bin ; ln -sf /bin/tar . )
-	( cd ${pkgdir}/bin ; ln -sf tar tar-${pkgver} )
-
-	# Support "historic" rmt locations:
-	mkdir -p ${pkgdir}/{etc,sbin}
-	( cd ${pkgdir}/etc
-		ln -sf /usr/libexec/rmt .
-		cd ${pkgdir}/sbin
-		ln -sf /usr/libexec/rmt .
-	)
-
-	mkdir -p ${pkgdir}/usr/man/man{1,8}
-	cat ${filedir}/tar.1.gz > ${pkgdir}/usr/man/man1/tar.1.gz
-	cat ${filedir}/rmt.8.gz > ${pkgdir}/usr/man/man8/rmt.8.gz
-
-	# Russian manual for tar
-	mkdir -p ${pkgdir}/usr/man/ru/man1
-	cat ${filedir}/tar.1-ru.gz > ${pkgdir}/usr/man/ru/man1/tar.1.gz
-
+build() {
+  go_src_dir
+  export FORCE_UNSAFE_CONFIGURE=1
+  ./configure \
+    --prefix=/usr \
+    --libexecdir=/usr/lib${LIBDIRSUFFIX}/tar
+  make -j${numjobs}
+  make DESTDIR=${pkgdir} install
 }
-
