Обновлён python2 2.7.18-2

diff --git a/develop/Python/python2/ABUILD b/develop/Python/python2/ABUILD
--- a/develop/Python/python2/ABUILD
+++ b/develop/Python/python2/ABUILD
@@ -1,9 +1,10 @@
 pkgname=python2
 pkgver=2.7.18
-pkgbuild=1
+pkgbuild=2
 arch=('auto')
 
-shortdesc=("python (object-oriented interpreted programming language)")
+shortdesc="An interpreted, interactive object-oriented programming language"
+longdesc="Python is an interpreted, interactive, object-oriented programming language often compared to Tcl, Perl, Scheme or Java. Python includes modules, classes, exceptions, very high level dynamic data types and dynamic typing. Python supports interfaces to many system calls and libraries, as well as to various windowing systems"
 
 source=("http://www.python.org/ftp/python/${pkgver}/Python-${pkgver}.tar.xz")
 
@@ -15,76 +16,66 @@ build_deps="openssl readline sqlite bzip2 gdbm expat libffi"
 
 before_build()
 {
-	go_src_dir
-	burn_patches
-	sed -i -e "s|^#.* /usr/local/bin/python|#!/usr/bin/python|" Lib/cgi.py
-	rm -r Modules/expat
-	rm -r Modules/zlib
-	rm -r Modules/_ctypes/{darwin,libffi}*
-	#lib64 related stuff
-#	if [ "$ARCH" = "x86_64" ] ; then
-#		# Install to lib64 instead of lib:
-#		patch -p1 < $filedir/python27.x86_64.diff || exit 1
-#	fi
+  go_src_dir
+  burn_patches
+  sed -i -e "s|^#.* /usr/local/bin/python|#!/usr/bin/python|" Lib/cgi.py
+  rm -r Modules/expat
+  rm -r Modules/zlib
+  rm -r Modules/_ctypes/{darwin,libffi}*
 }
 
 build() {
-	go_src_dir
-echo 7
-	./configure \
-	--prefix=/usr \
-	--sysconfdir=/etc \
-	--localstatedir=/var \
-	--disable-static \
-	--mandir=/usr/man \
-	--program-prefix= \
-	--program-suffix= \
-	--enable-shared \
-	--with-threads \
-	--with-computed-gotos \
-	--enable-ipv6 \
-	--with-system-expat \
-	--with-system-ffi \
-	--enable-unicode=ucs4 \
-	--with-dbmliborder=gdbm:ndbm
+  go_src_dir
+  ./configure \
+    --prefix=/usr \
+    --sysconfdir=/etc \
+    --localstatedir=/var \
+    --disable-static \
+    --program-prefix= \
+    --program-suffix= \
+    --enable-shared \
+    --with-threads \
+    --with-computed-gotos \
+    --enable-ipv6 \
+    --with-system-expat \
+    --with-system-ffi \
+    --enable-unicode=ucs4 \
+    --with-dbmliborder=gdbm:ndbm
+  make -j${numjobs} MACHDEP=linux2 || exit 1
 
-	make -j${numjobs} MACHDEP=linux2 || exit 1
 # Hack to avoid building again
   sed -i 's/^all:.*$/all: build_all/' Makefile
-	make DESTDIR=${pkgdir} altinstall maninstall || exit 1
+  make DESTDIR=${pkgdir} altinstall maninstall || exit 1
 }
 
-#ran after function build() 
-#после сборки
 after_build()
 {
   ln -sf python${pkgver%.*}        "${pkgdir}/usr/bin/python2"
   ln -sf python${pkgver%.*}-config "${pkgdir}/usr/bin/python2-config"
- # ln -sf python${pkgver%.*}.1      "${pkgdir}/usr/share/man/man1/python2.7"
 
   ln -sf ../../libpython${pkgver%.*}.so \
     "${pkgdir}/usr/lib/python${pkgver%.*}/config/libpython${pkgver%.*}.so"
 
   mv "${pkgdir}/usr/bin/smtpd.py" "${pkgdir}/usr/lib/python${pkgver%.*}/"
 
-  # some useful "stuff"
+# some useful "stuff"
   install -dm755 "${pkgdir}"/usr/lib/python${pkgver%.*}/Tools/{i18n,scripts}
   install -m755 Tools/i18n/{msgfmt,pygettext}.py \
     "${pkgdir}/usr/lib/python${pkgver%.*}/Tools/i18n/"
   install -m755 Tools/scripts/{README,*py} \
     "${pkgdir}/usr/lib/python${pkgver%.*}/Tools/scripts/"
 
-  # fix conflicts with python
+# fix conflicts with python
   mv "${pkgdir}"/usr/bin/idle{,27}
   mv "${pkgdir}"/usr/bin/pydoc{,27}
   mv "${pkgdir}"/usr/bin/2to3{,-2.7}
   rm "${pkgdir}"/usr/bin/python2{,-config}
 
-  # clean up #!s
+# clean up #!s
   find "${pkgdir}/usr/lib/python${pkgver%.*}/" -name '*.py' | \
     xargs sed -i "s|#[ ]*![ ]*/usr/bin/env python$|#!/usr/bin/env python27|"
 
-  # clean-up reference to build directory
+# clean-up reference to build directory
   sed -i "s#${srcdir}/Python-${pkgver}:##" \
     "${pkgdir}/usr/lib/python${pkgver%.*}/config/Makefile"
 }
